# =============================================================================
#  Misc and XWayland
#  https://wiki.hypr.land/0.54.0/Configuring/Variables/#misc
#  https://wiki.hypr.land/0.54.0/Configuring/XWayland/
# =============================================================================

misc {
    force_default_wallpaper = 0    # 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true   # disables the random hyprland logo background
}

xwayland {
    force_zero_scaling = true
}
