# =============================================================================
#  Monitors
#  https://wiki.hypr.land/0.54.0/Configuring/Monitors/
# =============================================================================

monitor=,preferred,auto,1.333
