# vim:set ft=tmux:
%hidden MODULE_NAME="netspeed"

set -ogq @catppuccin_netspeed_icon "󰓅 "
set -ogqF @catppuccin_netspeed_color "#{E:@thm_teal}"
set -ogq @catppuccin_netspeed_text " #(/Users/rifuki/.config/tmux/scripts/net_speed.sh max)"

source -F "#{d:current_file}/../plugins/tmux/utils/status_module.conf"
