-- =============================================================================
--  Hyprland — entry point
-- =============================================================================
--  This file only wires modules together. Put actual settings in conf/*.lua.
--
--  WHY LUA: Hyprland >=0.55 deprecated hyprlang, and `main` (development toward
--  0.57) has already deleted src/config/legacy entirely. 0.56.2 still falls back
--  to hyprland.conf when no hyprland.lua exists, so the old config kept working
--  — but that fallback disappears in 0.57. This file being present means the Lua
--  path is used and hyprland.conf is ignored.
--
--  ROLLBACK: rename this file (e.g. hyprland.lua.off). Hyprland then finds no Lua
--  config and reads hyprland.conf again, which is still on disk beside it.
--
--  Each require() gets its own Lua scope, so a runtime error in one module does
--  not abort the others. Loading a module that does not exist IS fatal, however
--  — require() throws in the caller's scope.
--
--  API reference: /usr/share/hypr/stubs/hl.meta.lua (autogenerated from source).
--  Point your LSP at it via .luarc.json for completion on hl.*.
-- =============================================================================

require("conf/monitors")
require("conf/env")
require("conf/autostart")
require("conf/permissions")
require("conf/looknfeel")
require("conf/layouts")
require("conf/input")
require("conf/gestures")
require("conf/keybinds")
require("conf/windowrules")
require("conf/misc")

-- conf/programs.lua is deliberately absent above: it returns a table of program
-- names rather than calling hl.*, and keybinds.lua requires it directly.
